# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "clink15/pxe"
  config.vm.box_version = "2"
  config.vm.network "private_network", type: "dhcp"
  config.vm.communicator = "non-existing"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--nattftpserver1", "10.0.2.2"]
    v.customize ["modifyvm", :id, "--nattftpfile1", "http://10.0.2.2:8080/ipxe?uuid=test"]
  end
end
