// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storagepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Group selects one or more machines and matches them to a Profile.
type Group struct {
	// machine readable Id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// human readable name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Profile id
	Profile string `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
	// Selectors to match machines
	Selector map[string]string `protobuf:"bytes,4,rep,name=selector" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// JSON encoded metadata
	Metadata             []byte   `protobuf:"bytes,15,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_6eaf31db8c4cbddb, []int{0}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *Group) GetSelector() map[string]string {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *Group) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Profile defines the boot and provisioning behavior of a group of machines.
type Profile struct {
	// profile id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// human readable name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Bound templates to this profile
	Template map[string]string `protobuf:"bytes,14,rep,name=template" json:"template,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// JSON encoded metadata
	Metadata             []byte   `protobuf:"bytes,15,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_6eaf31db8c4cbddb, []int{1}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetTemplate() map[string]string {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *Profile) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Template struct {
	// template id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// human readable name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// template contents
	Contents             []byte   `protobuf:"bytes,15,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_6eaf31db8c4cbddb, []int{2}
}
func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (dst *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(dst, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Template) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Template) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func init() {
	proto.RegisterType((*Group)(nil), "storagepb.Group")
	proto.RegisterMapType((map[string]string)(nil), "storagepb.Group.SelectorEntry")
	proto.RegisterType((*Profile)(nil), "storagepb.Profile")
	proto.RegisterMapType((map[string]string)(nil), "storagepb.Profile.TemplateEntry")
	proto.RegisterType((*Template)(nil), "storagepb.Template")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_storage_6eaf31db8c4cbddb) }

var fileDescriptor_storage_6eaf31db8c4cbddb = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0xc4, 0x69, 0xdd, 0x2b, 0x2d, 0x91, 0xc5, 0x60, 0x75, 0x40, 0x51, 0xa7, 0x4e,
	0x19, 0x60, 0x41, 0x85, 0x15, 0x21, 0x65, 0x42, 0x81, 0xbd, 0x72, 0x93, 0xa3, 0xb2, 0x48, 0xed,
	0xc8, 0xbd, 0x22, 0xf5, 0x07, 0xf0, 0x27, 0xf9, 0x35, 0xa8, 0xc1, 0x89, 0xe8, 0x44, 0xd9, 0xee,
	0x9d, 0xee, 0xe5, 0xbd, 0x2f, 0x32, 0x4c, 0x76, 0x64, 0x9d, 0xda, 0x60, 0xd6, 0x38, 0x4b, 0x56,
	0x8c, 0xbc, 0x6c, 0xd6, 0xf3, 0xaf, 0x00, 0xe2, 0x27, 0x67, 0xf7, 0x8d, 0x98, 0x42, 0xa8, 0x2b,
	0x19, 0xa4, 0xc1, 0x62, 0x54, 0x84, 0xba, 0x12, 0x02, 0x98, 0x51, 0x5b, 0x94, 0x61, 0xbb, 0x69,
	0x67, 0x21, 0x61, 0xd8, 0x38, 0xfb, 0xa6, 0x6b, 0x94, 0x51, 0xbb, 0xee, 0xa4, 0x58, 0x02, 0xdf,
	0x61, 0x8d, 0x25, 0x59, 0x27, 0x59, 0x1a, 0x2d, 0xc6, 0x37, 0xd7, 0x59, 0x9f, 0x92, 0xb5, 0x09,
	0xd9, 0x8b, 0x3f, 0x78, 0x34, 0xe4, 0x0e, 0x45, 0x7f, 0x2f, 0x66, 0xc0, 0xb7, 0x48, 0xaa, 0x52,
	0xa4, 0xe4, 0x65, 0x1a, 0x2c, 0x2e, 0x8a, 0x5e, 0xcf, 0xee, 0x61, 0x72, 0x62, 0x13, 0x09, 0x44,
	0xef, 0x78, 0xf0, 0x3d, 0x8f, 0xa3, 0xb8, 0x82, 0xf8, 0x43, 0xd5, 0xfb, 0xae, 0xe9, 0x8f, 0x58,
	0x86, 0x77, 0xc1, 0xfc, 0x33, 0x84, 0xe1, 0xb3, 0x2f, 0x78, 0x0e, 0xde, 0x03, 0x70, 0xc2, 0x6d,
	0x53, 0x2b, 0x42, 0x39, 0x6d, 0x21, 0xd2, 0x5f, 0x10, 0xfe, 0x4b, 0xd9, 0xab, 0x3f, 0xf1, 0x18,
	0x9d, 0xe3, 0x2f, 0x8c, 0x13, 0xdb, 0x7f, 0x30, 0x72, 0xc6, 0xa3, 0x84, 0xe5, 0x8c, 0xb3, 0x24,
	0xce, 0x19, 0x8f, 0x93, 0x41, 0xce, 0xf8, 0x20, 0x19, 0x16, 0x63, 0xbd, 0x31, 0x9a, 0xb4, 0x35,
	0x2b, 0x5d, 0x15, 0xbc, 0xac, 0xed, 0xbe, 0x3a, 0x4e, 0x6c, 0x6d, 0x2d, 0x15, 0xb0, 0x41, 0x83,
	0x4e, 0x97, 0x2b, 0x5d, 0xcd, 0x73, 0xe0, 0x5d, 0xfa, 0x59, 0xff, 0x61, 0x06, 0xbc, 0xb4, 0x86,
	0xd0, 0xd0, 0xae, 0x23, 0xe9, 0xf4, 0x7a, 0xd0, 0x3e, 0xa1, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4e, 0x3c, 0x24, 0x44, 0x53, 0x02, 0x00, 0x00,
}
