language: go
sudo: required
services:
  - docker
go:
  - 1.7.x
  - 1.8.x
  - 1.8.5
  - 1.9.x
  - tip
matrix:
  allow_failures:
    - go: tip
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - go get github.com/golang/lint/golint
  - dep ensure
script:
  - make test
deploy:
  provider: script
  script: scripts/dev/travis-docker-push
  skip_cleanup: true
  on:
    branch: master
    go: '1.8.5'
notifications:
  email: change
