// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package serverpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import storagepb "github.com/coreos/matchbox/matchbox/storage/storagepb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SelectGroupRequest struct {
	Labels               map[string]string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SelectGroupRequest) Reset()         { *m = SelectGroupRequest{} }
func (m *SelectGroupRequest) String() string { return proto.CompactTextString(m) }
func (*SelectGroupRequest) ProtoMessage()    {}
func (*SelectGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{0}
}
func (m *SelectGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectGroupRequest.Unmarshal(m, b)
}
func (m *SelectGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectGroupRequest.Marshal(b, m, deterministic)
}
func (dst *SelectGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectGroupRequest.Merge(dst, src)
}
func (m *SelectGroupRequest) XXX_Size() int {
	return xxx_messageInfo_SelectGroupRequest.Size(m)
}
func (m *SelectGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectGroupRequest proto.InternalMessageInfo

func (m *SelectGroupRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type SelectGroupResponse struct {
	Group                *storagepb.Group `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SelectGroupResponse) Reset()         { *m = SelectGroupResponse{} }
func (m *SelectGroupResponse) String() string { return proto.CompactTextString(m) }
func (*SelectGroupResponse) ProtoMessage()    {}
func (*SelectGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{1}
}
func (m *SelectGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectGroupResponse.Unmarshal(m, b)
}
func (m *SelectGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectGroupResponse.Marshal(b, m, deterministic)
}
func (dst *SelectGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectGroupResponse.Merge(dst, src)
}
func (m *SelectGroupResponse) XXX_Size() int {
	return xxx_messageInfo_SelectGroupResponse.Size(m)
}
func (m *SelectGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelectGroupResponse proto.InternalMessageInfo

func (m *SelectGroupResponse) GetGroup() *storagepb.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type SelectProfileRequest struct {
	Labels               map[string]string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SelectProfileRequest) Reset()         { *m = SelectProfileRequest{} }
func (m *SelectProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SelectProfileRequest) ProtoMessage()    {}
func (*SelectProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{2}
}
func (m *SelectProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectProfileRequest.Unmarshal(m, b)
}
func (m *SelectProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectProfileRequest.Marshal(b, m, deterministic)
}
func (dst *SelectProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectProfileRequest.Merge(dst, src)
}
func (m *SelectProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SelectProfileRequest.Size(m)
}
func (m *SelectProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectProfileRequest proto.InternalMessageInfo

func (m *SelectProfileRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type SelectProfileResponse struct {
	Profile              *storagepb.Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SelectProfileResponse) Reset()         { *m = SelectProfileResponse{} }
func (m *SelectProfileResponse) String() string { return proto.CompactTextString(m) }
func (*SelectProfileResponse) ProtoMessage()    {}
func (*SelectProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{3}
}
func (m *SelectProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectProfileResponse.Unmarshal(m, b)
}
func (m *SelectProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectProfileResponse.Marshal(b, m, deterministic)
}
func (dst *SelectProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectProfileResponse.Merge(dst, src)
}
func (m *SelectProfileResponse) XXX_Size() int {
	return xxx_messageInfo_SelectProfileResponse.Size(m)
}
func (m *SelectProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SelectProfileResponse proto.InternalMessageInfo

func (m *SelectProfileResponse) GetProfile() *storagepb.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type GroupPutRequest struct {
	Group                *storagepb.Group `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GroupPutRequest) Reset()         { *m = GroupPutRequest{} }
func (m *GroupPutRequest) String() string { return proto.CompactTextString(m) }
func (*GroupPutRequest) ProtoMessage()    {}
func (*GroupPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{4}
}
func (m *GroupPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPutRequest.Unmarshal(m, b)
}
func (m *GroupPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPutRequest.Marshal(b, m, deterministic)
}
func (dst *GroupPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPutRequest.Merge(dst, src)
}
func (m *GroupPutRequest) XXX_Size() int {
	return xxx_messageInfo_GroupPutRequest.Size(m)
}
func (m *GroupPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPutRequest proto.InternalMessageInfo

func (m *GroupPutRequest) GetGroup() *storagepb.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupPutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupPutResponse) Reset()         { *m = GroupPutResponse{} }
func (m *GroupPutResponse) String() string { return proto.CompactTextString(m) }
func (*GroupPutResponse) ProtoMessage()    {}
func (*GroupPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{5}
}
func (m *GroupPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupPutResponse.Unmarshal(m, b)
}
func (m *GroupPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupPutResponse.Marshal(b, m, deterministic)
}
func (dst *GroupPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupPutResponse.Merge(dst, src)
}
func (m *GroupPutResponse) XXX_Size() int {
	return xxx_messageInfo_GroupPutResponse.Size(m)
}
func (m *GroupPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupPutResponse proto.InternalMessageInfo

type GroupGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupGetRequest) Reset()         { *m = GroupGetRequest{} }
func (m *GroupGetRequest) String() string { return proto.CompactTextString(m) }
func (*GroupGetRequest) ProtoMessage()    {}
func (*GroupGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{6}
}
func (m *GroupGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupGetRequest.Unmarshal(m, b)
}
func (m *GroupGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupGetRequest.Marshal(b, m, deterministic)
}
func (dst *GroupGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupGetRequest.Merge(dst, src)
}
func (m *GroupGetRequest) XXX_Size() int {
	return xxx_messageInfo_GroupGetRequest.Size(m)
}
func (m *GroupGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupGetRequest proto.InternalMessageInfo

func (m *GroupGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GroupGetResponse struct {
	Group                *storagepb.Group `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GroupGetResponse) Reset()         { *m = GroupGetResponse{} }
func (m *GroupGetResponse) String() string { return proto.CompactTextString(m) }
func (*GroupGetResponse) ProtoMessage()    {}
func (*GroupGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{7}
}
func (m *GroupGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupGetResponse.Unmarshal(m, b)
}
func (m *GroupGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupGetResponse.Marshal(b, m, deterministic)
}
func (dst *GroupGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupGetResponse.Merge(dst, src)
}
func (m *GroupGetResponse) XXX_Size() int {
	return xxx_messageInfo_GroupGetResponse.Size(m)
}
func (m *GroupGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupGetResponse proto.InternalMessageInfo

func (m *GroupGetResponse) GetGroup() *storagepb.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type GroupDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupDeleteRequest) Reset()         { *m = GroupDeleteRequest{} }
func (m *GroupDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*GroupDeleteRequest) ProtoMessage()    {}
func (*GroupDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{8}
}
func (m *GroupDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupDeleteRequest.Unmarshal(m, b)
}
func (m *GroupDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *GroupDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupDeleteRequest.Merge(dst, src)
}
func (m *GroupDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_GroupDeleteRequest.Size(m)
}
func (m *GroupDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupDeleteRequest proto.InternalMessageInfo

func (m *GroupDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GroupDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupDeleteResponse) Reset()         { *m = GroupDeleteResponse{} }
func (m *GroupDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*GroupDeleteResponse) ProtoMessage()    {}
func (*GroupDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{9}
}
func (m *GroupDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupDeleteResponse.Unmarshal(m, b)
}
func (m *GroupDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupDeleteResponse.Marshal(b, m, deterministic)
}
func (dst *GroupDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupDeleteResponse.Merge(dst, src)
}
func (m *GroupDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_GroupDeleteResponse.Size(m)
}
func (m *GroupDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupDeleteResponse proto.InternalMessageInfo

type GroupListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupListRequest) Reset()         { *m = GroupListRequest{} }
func (m *GroupListRequest) String() string { return proto.CompactTextString(m) }
func (*GroupListRequest) ProtoMessage()    {}
func (*GroupListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{10}
}
func (m *GroupListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupListRequest.Unmarshal(m, b)
}
func (m *GroupListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupListRequest.Marshal(b, m, deterministic)
}
func (dst *GroupListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupListRequest.Merge(dst, src)
}
func (m *GroupListRequest) XXX_Size() int {
	return xxx_messageInfo_GroupListRequest.Size(m)
}
func (m *GroupListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupListRequest proto.InternalMessageInfo

type GroupListResponse struct {
	Groups               []*storagepb.Group `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GroupListResponse) Reset()         { *m = GroupListResponse{} }
func (m *GroupListResponse) String() string { return proto.CompactTextString(m) }
func (*GroupListResponse) ProtoMessage()    {}
func (*GroupListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{11}
}
func (m *GroupListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupListResponse.Unmarshal(m, b)
}
func (m *GroupListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupListResponse.Marshal(b, m, deterministic)
}
func (dst *GroupListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupListResponse.Merge(dst, src)
}
func (m *GroupListResponse) XXX_Size() int {
	return xxx_messageInfo_GroupListResponse.Size(m)
}
func (m *GroupListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupListResponse proto.InternalMessageInfo

func (m *GroupListResponse) GetGroups() []*storagepb.Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type ProfilePutRequest struct {
	Profile              *storagepb.Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProfilePutRequest) Reset()         { *m = ProfilePutRequest{} }
func (m *ProfilePutRequest) String() string { return proto.CompactTextString(m) }
func (*ProfilePutRequest) ProtoMessage()    {}
func (*ProfilePutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{12}
}
func (m *ProfilePutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePutRequest.Unmarshal(m, b)
}
func (m *ProfilePutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePutRequest.Marshal(b, m, deterministic)
}
func (dst *ProfilePutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePutRequest.Merge(dst, src)
}
func (m *ProfilePutRequest) XXX_Size() int {
	return xxx_messageInfo_ProfilePutRequest.Size(m)
}
func (m *ProfilePutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePutRequest proto.InternalMessageInfo

func (m *ProfilePutRequest) GetProfile() *storagepb.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type ProfilePutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfilePutResponse) Reset()         { *m = ProfilePutResponse{} }
func (m *ProfilePutResponse) String() string { return proto.CompactTextString(m) }
func (*ProfilePutResponse) ProtoMessage()    {}
func (*ProfilePutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{13}
}
func (m *ProfilePutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePutResponse.Unmarshal(m, b)
}
func (m *ProfilePutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePutResponse.Marshal(b, m, deterministic)
}
func (dst *ProfilePutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePutResponse.Merge(dst, src)
}
func (m *ProfilePutResponse) XXX_Size() int {
	return xxx_messageInfo_ProfilePutResponse.Size(m)
}
func (m *ProfilePutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePutResponse proto.InternalMessageInfo

type ProfileGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileGetRequest) Reset()         { *m = ProfileGetRequest{} }
func (m *ProfileGetRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileGetRequest) ProtoMessage()    {}
func (*ProfileGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{14}
}
func (m *ProfileGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileGetRequest.Unmarshal(m, b)
}
func (m *ProfileGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileGetRequest.Marshal(b, m, deterministic)
}
func (dst *ProfileGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileGetRequest.Merge(dst, src)
}
func (m *ProfileGetRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileGetRequest.Size(m)
}
func (m *ProfileGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileGetRequest proto.InternalMessageInfo

func (m *ProfileGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProfileGetResponse struct {
	Profile              *storagepb.Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProfileGetResponse) Reset()         { *m = ProfileGetResponse{} }
func (m *ProfileGetResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileGetResponse) ProtoMessage()    {}
func (*ProfileGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{15}
}
func (m *ProfileGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileGetResponse.Unmarshal(m, b)
}
func (m *ProfileGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileGetResponse.Marshal(b, m, deterministic)
}
func (dst *ProfileGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileGetResponse.Merge(dst, src)
}
func (m *ProfileGetResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileGetResponse.Size(m)
}
func (m *ProfileGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileGetResponse proto.InternalMessageInfo

func (m *ProfileGetResponse) GetProfile() *storagepb.Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type ProfileDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDeleteRequest) Reset()         { *m = ProfileDeleteRequest{} }
func (m *ProfileDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileDeleteRequest) ProtoMessage()    {}
func (*ProfileDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{16}
}
func (m *ProfileDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDeleteRequest.Unmarshal(m, b)
}
func (m *ProfileDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *ProfileDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDeleteRequest.Merge(dst, src)
}
func (m *ProfileDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileDeleteRequest.Size(m)
}
func (m *ProfileDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDeleteRequest proto.InternalMessageInfo

func (m *ProfileDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProfileDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileDeleteResponse) Reset()         { *m = ProfileDeleteResponse{} }
func (m *ProfileDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileDeleteResponse) ProtoMessage()    {}
func (*ProfileDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{17}
}
func (m *ProfileDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileDeleteResponse.Unmarshal(m, b)
}
func (m *ProfileDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileDeleteResponse.Marshal(b, m, deterministic)
}
func (dst *ProfileDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileDeleteResponse.Merge(dst, src)
}
func (m *ProfileDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileDeleteResponse.Size(m)
}
func (m *ProfileDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileDeleteResponse proto.InternalMessageInfo

type ProfileListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileListRequest) Reset()         { *m = ProfileListRequest{} }
func (m *ProfileListRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileListRequest) ProtoMessage()    {}
func (*ProfileListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{18}
}
func (m *ProfileListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileListRequest.Unmarshal(m, b)
}
func (m *ProfileListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileListRequest.Marshal(b, m, deterministic)
}
func (dst *ProfileListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileListRequest.Merge(dst, src)
}
func (m *ProfileListRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileListRequest.Size(m)
}
func (m *ProfileListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileListRequest proto.InternalMessageInfo

type ProfileListResponse struct {
	Profiles             []*storagepb.Profile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProfileListResponse) Reset()         { *m = ProfileListResponse{} }
func (m *ProfileListResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileListResponse) ProtoMessage()    {}
func (*ProfileListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{19}
}
func (m *ProfileListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileListResponse.Unmarshal(m, b)
}
func (m *ProfileListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileListResponse.Marshal(b, m, deterministic)
}
func (dst *ProfileListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileListResponse.Merge(dst, src)
}
func (m *ProfileListResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileListResponse.Size(m)
}
func (m *ProfileListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileListResponse proto.InternalMessageInfo

func (m *ProfileListResponse) GetProfiles() []*storagepb.Profile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type TemplatePutRequest struct {
	Template             *storagepb.Template `protobuf:"bytes,1,opt,name=template" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TemplatePutRequest) Reset()         { *m = TemplatePutRequest{} }
func (m *TemplatePutRequest) String() string { return proto.CompactTextString(m) }
func (*TemplatePutRequest) ProtoMessage()    {}
func (*TemplatePutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{20}
}
func (m *TemplatePutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplatePutRequest.Unmarshal(m, b)
}
func (m *TemplatePutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplatePutRequest.Marshal(b, m, deterministic)
}
func (dst *TemplatePutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplatePutRequest.Merge(dst, src)
}
func (m *TemplatePutRequest) XXX_Size() int {
	return xxx_messageInfo_TemplatePutRequest.Size(m)
}
func (m *TemplatePutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplatePutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TemplatePutRequest proto.InternalMessageInfo

func (m *TemplatePutRequest) GetTemplate() *storagepb.Template {
	if m != nil {
		return m.Template
	}
	return nil
}

type TemplatePutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplatePutResponse) Reset()         { *m = TemplatePutResponse{} }
func (m *TemplatePutResponse) String() string { return proto.CompactTextString(m) }
func (*TemplatePutResponse) ProtoMessage()    {}
func (*TemplatePutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{21}
}
func (m *TemplatePutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplatePutResponse.Unmarshal(m, b)
}
func (m *TemplatePutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplatePutResponse.Marshal(b, m, deterministic)
}
func (dst *TemplatePutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplatePutResponse.Merge(dst, src)
}
func (m *TemplatePutResponse) XXX_Size() int {
	return xxx_messageInfo_TemplatePutResponse.Size(m)
}
func (m *TemplatePutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplatePutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TemplatePutResponse proto.InternalMessageInfo

type TemplateGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateGetRequest) Reset()         { *m = TemplateGetRequest{} }
func (m *TemplateGetRequest) String() string { return proto.CompactTextString(m) }
func (*TemplateGetRequest) ProtoMessage()    {}
func (*TemplateGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{22}
}
func (m *TemplateGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateGetRequest.Unmarshal(m, b)
}
func (m *TemplateGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateGetRequest.Marshal(b, m, deterministic)
}
func (dst *TemplateGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateGetRequest.Merge(dst, src)
}
func (m *TemplateGetRequest) XXX_Size() int {
	return xxx_messageInfo_TemplateGetRequest.Size(m)
}
func (m *TemplateGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateGetRequest proto.InternalMessageInfo

func (m *TemplateGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TemplateGetResponse struct {
	Template             *storagepb.Template `protobuf:"bytes,1,opt,name=template" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TemplateGetResponse) Reset()         { *m = TemplateGetResponse{} }
func (m *TemplateGetResponse) String() string { return proto.CompactTextString(m) }
func (*TemplateGetResponse) ProtoMessage()    {}
func (*TemplateGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{23}
}
func (m *TemplateGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateGetResponse.Unmarshal(m, b)
}
func (m *TemplateGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateGetResponse.Marshal(b, m, deterministic)
}
func (dst *TemplateGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateGetResponse.Merge(dst, src)
}
func (m *TemplateGetResponse) XXX_Size() int {
	return xxx_messageInfo_TemplateGetResponse.Size(m)
}
func (m *TemplateGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateGetResponse proto.InternalMessageInfo

func (m *TemplateGetResponse) GetTemplate() *storagepb.Template {
	if m != nil {
		return m.Template
	}
	return nil
}

type TemplateDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateDeleteRequest) Reset()         { *m = TemplateDeleteRequest{} }
func (m *TemplateDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*TemplateDeleteRequest) ProtoMessage()    {}
func (*TemplateDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{24}
}
func (m *TemplateDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateDeleteRequest.Unmarshal(m, b)
}
func (m *TemplateDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateDeleteRequest.Marshal(b, m, deterministic)
}
func (dst *TemplateDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateDeleteRequest.Merge(dst, src)
}
func (m *TemplateDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_TemplateDeleteRequest.Size(m)
}
func (m *TemplateDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateDeleteRequest proto.InternalMessageInfo

func (m *TemplateDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TemplateDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateDeleteResponse) Reset()         { *m = TemplateDeleteResponse{} }
func (m *TemplateDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*TemplateDeleteResponse) ProtoMessage()    {}
func (*TemplateDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1861542c9149b96d, []int{25}
}
func (m *TemplateDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateDeleteResponse.Unmarshal(m, b)
}
func (m *TemplateDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateDeleteResponse.Marshal(b, m, deterministic)
}
func (dst *TemplateDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateDeleteResponse.Merge(dst, src)
}
func (m *TemplateDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_TemplateDeleteResponse.Size(m)
}
func (m *TemplateDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateDeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SelectGroupRequest)(nil), "serverpb.SelectGroupRequest")
	proto.RegisterMapType((map[string]string)(nil), "serverpb.SelectGroupRequest.LabelsEntry")
	proto.RegisterType((*SelectGroupResponse)(nil), "serverpb.SelectGroupResponse")
	proto.RegisterType((*SelectProfileRequest)(nil), "serverpb.SelectProfileRequest")
	proto.RegisterMapType((map[string]string)(nil), "serverpb.SelectProfileRequest.LabelsEntry")
	proto.RegisterType((*SelectProfileResponse)(nil), "serverpb.SelectProfileResponse")
	proto.RegisterType((*GroupPutRequest)(nil), "serverpb.GroupPutRequest")
	proto.RegisterType((*GroupPutResponse)(nil), "serverpb.GroupPutResponse")
	proto.RegisterType((*GroupGetRequest)(nil), "serverpb.GroupGetRequest")
	proto.RegisterType((*GroupGetResponse)(nil), "serverpb.GroupGetResponse")
	proto.RegisterType((*GroupDeleteRequest)(nil), "serverpb.GroupDeleteRequest")
	proto.RegisterType((*GroupDeleteResponse)(nil), "serverpb.GroupDeleteResponse")
	proto.RegisterType((*GroupListRequest)(nil), "serverpb.GroupListRequest")
	proto.RegisterType((*GroupListResponse)(nil), "serverpb.GroupListResponse")
	proto.RegisterType((*ProfilePutRequest)(nil), "serverpb.ProfilePutRequest")
	proto.RegisterType((*ProfilePutResponse)(nil), "serverpb.ProfilePutResponse")
	proto.RegisterType((*ProfileGetRequest)(nil), "serverpb.ProfileGetRequest")
	proto.RegisterType((*ProfileGetResponse)(nil), "serverpb.ProfileGetResponse")
	proto.RegisterType((*ProfileDeleteRequest)(nil), "serverpb.ProfileDeleteRequest")
	proto.RegisterType((*ProfileDeleteResponse)(nil), "serverpb.ProfileDeleteResponse")
	proto.RegisterType((*ProfileListRequest)(nil), "serverpb.ProfileListRequest")
	proto.RegisterType((*ProfileListResponse)(nil), "serverpb.ProfileListResponse")
	proto.RegisterType((*TemplatePutRequest)(nil), "serverpb.TemplatePutRequest")
	proto.RegisterType((*TemplatePutResponse)(nil), "serverpb.TemplatePutResponse")
	proto.RegisterType((*TemplateGetRequest)(nil), "serverpb.TemplateGetRequest")
	proto.RegisterType((*TemplateGetResponse)(nil), "serverpb.TemplateGetResponse")
	proto.RegisterType((*TemplateDeleteRequest)(nil), "serverpb.TemplateDeleteRequest")
	proto.RegisterType((*TemplateDeleteResponse)(nil), "serverpb.TemplateDeleteResponse")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_1861542c9149b96d) }

var fileDescriptor_messages_1861542c9149b96d = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x57, 0x3a, 0xad, 0x94, 0x57, 0x69, 0x74, 0x6e, 0x0b, 0xd5, 0x4e, 0xc3, 0x4c, 0xa3, 0x42,
	0xc8, 0x95, 0xc6, 0x85, 0x4d, 0x9a, 0x04, 0x83, 0xb2, 0xcb, 0x0e, 0x53, 0xe1, 0x0b, 0x24, 0xdd,
	0xa3, 0x8b, 0x48, 0xe7, 0x60, 0x3b, 0x13, 0xfb, 0x18, 0x1c, 0xf8, 0xbe, 0xa8, 0xf6, 0x73, 0xe2,
	0xa4, 0x50, 0x51, 0x89, 0x53, 0x9d, 0x97, 0xdf, 0xfb, 0xfd, 0x73, 0x15, 0xd8, 0x5b, 0xa2, 0xd6,
	0xf1, 0x02, 0xb5, 0xc8, 0x95, 0x34, 0x92, 0x75, 0x34, 0xaa, 0x7b, 0x54, 0x79, 0x72, 0xf0, 0x61,
	0x91, 0x9a, 0xdb, 0x22, 0x11, 0x73, 0xb9, 0x9c, 0xcc, 0xa5, 0x42, 0xa9, 0x27, 0xcb, 0xd8, 0xcc,
	0x6f, 0x13, 0xf9, 0xa3, 0x3a, 0x68, 0x23, 0x55, 0xbc, 0x40, 0xff, 0x9b, 0x27, 0xfe, 0xe4, 0xe8,
	0xf8, 0xcf, 0x08, 0xd8, 0x67, 0xcc, 0x70, 0x6e, 0x2e, 0x95, 0x2c, 0xf2, 0x19, 0x7e, 0x2f, 0x50,
	0x1b, 0xf6, 0x0e, 0xda, 0x59, 0x9c, 0x60, 0xa6, 0x47, 0xd1, 0xe1, 0xce, 0xb8, 0x7b, 0x32, 0x16,
	0x5e, 0x56, 0xac, 0xa3, 0xc5, 0x95, 0x85, 0x4e, 0xef, 0x8c, 0x7a, 0x98, 0xd1, 0xde, 0xc1, 0x29,
	0x74, 0x83, 0x31, 0xeb, 0xc1, 0xce, 0x37, 0x7c, 0x18, 0x45, 0x87, 0xd1, 0xf8, 0xf1, 0x6c, 0x75,
	0x64, 0x03, 0xd8, 0xbd, 0x8f, 0xb3, 0x02, 0x47, 0x2d, 0x3b, 0x73, 0x0f, 0x67, 0xad, 0xb7, 0x11,
	0x3f, 0x87, 0x7e, 0x4d, 0x44, 0xe7, 0xf2, 0x4e, 0x23, 0x3b, 0x86, 0xdd, 0xc5, 0x6a, 0x60, 0x49,
	0xba, 0x27, 0x3d, 0x51, 0x66, 0x12, 0x0e, 0xe8, 0x5e, 0xf3, 0x5f, 0x11, 0x0c, 0xdc, 0xfe, 0xb5,
	0x92, 0x5f, 0xd3, 0x0c, 0x7d, 0xa8, 0x8b, 0x46, 0xa8, 0x57, 0xcd, 0x50, 0x75, 0xfc, 0xff, 0x8e,
	0x35, 0x85, 0x61, 0x43, 0x86, 0x82, 0xbd, 0x86, 0x47, 0xb9, 0x1b, 0x51, 0x34, 0x16, 0x44, 0xf3,
	0x60, 0x0f, 0xe1, 0xa7, 0xf0, 0xc4, 0xc6, 0xbd, 0x2e, 0x8c, 0x0f, 0xf6, 0xaf, 0xcd, 0x30, 0xe8,
	0x55, 0xab, 0x4e, 0x9c, 0x3f, 0x27, 0xba, 0x4b, 0x2c, 0xe9, 0xf6, 0xa0, 0x95, 0xde, 0x50, 0xa6,
	0x56, 0x7a, 0xc3, 0xcf, 0x68, 0xcd, 0x42, 0xb6, 0xbc, 0x8c, 0x23, 0x60, 0xf6, 0xf9, 0x23, 0x66,
	0x68, 0xf0, 0x6f, 0x0a, 0x43, 0xe8, 0xd7, 0x50, 0xe4, 0xcd, 0xfb, 0xbd, 0x4a, 0xb5, 0x37, 0xc7,
	0xcf, 0x61, 0x3f, 0x98, 0x91, 0x9b, 0x31, 0xb4, 0xad, 0x9c, 0xbf, 0xd9, 0x75, 0x3b, 0xf4, 0x9e,
	0xbf, 0x87, 0x7d, 0x6a, 0x34, 0xe8, 0x6f, 0xbb, 0x0b, 0x18, 0x00, 0x0b, 0x29, 0xc8, 0xeb, 0x8b,
	0x92, 0x78, 0x43, 0x93, 0x17, 0xe5, 0x6a, 0xd8, 0xe5, 0x76, 0xf2, 0xc7, 0x30, 0xa0, 0xd9, 0xe6,
	0x4e, 0x9f, 0xc1, 0xb0, 0x81, 0x23, 0xa7, 0x95, 0xff, 0xb0, 0xd7, 0x29, 0xf4, 0x6b, 0x53, 0xf2,
	0x26, 0xa0, 0x43, 0xc2, 0xbe, 0xdb, 0x3f, 0x99, 0x2b, 0x31, 0x7c, 0x0a, 0xec, 0x0b, 0x2e, 0xf3,
	0x2c, 0x36, 0x61, 0xc1, 0x13, 0xe8, 0x18, 0x9a, 0x52, 0xc4, 0x7e, 0xc0, 0xe2, 0x17, 0x66, 0x25,
	0x68, 0xf5, 0x87, 0xa8, 0xd1, 0x90, 0xf5, 0xa3, 0x8a, 0x7d, 0x43, 0xcb, 0x9f, 0xaa, 0xe5, 0xb0,
	0xe6, 0xad, 0x4d, 0xbc, 0x84, 0xa1, 0x9f, 0x6e, 0xae, 0x7a, 0x04, 0x4f, 0x9b, 0x40, 0xa7, 0x99,
	0xb4, 0xed, 0x57, 0xf6, 0xcd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x97, 0x60, 0xca, 0xc6,
	0x05, 0x00, 0x00,
}
